### ISSUE TITLE
Release the source code

### ISSUE THREAD

**Issue by janpetras** [FascinatedBox/RuinMyHistory#11]
Since it seems that you've more or less abbandoned the project, may I ask: why not just release the source code and let us improve on it ourselves? I'd love to turn this into a full-blown extension or some other mechanism that works better.

**Comment by damanbaird** [comment]
agree...

**Comment by FascinatedBox** [comment]
@damanbaird, thanks for bumping this. It's been a long time since I've signed on here, and I completely forgot that I even wrote this. The original poster is right about this being abandoned.

As for the source code, it's in the gh-pages branch. Sorry for not including that in the readme. I'm going to do some final housekeeping, which will include adding that to the readme.
