### ISSUE TITLE
Configurable interval

### ISSUE THREAD

**Issue by FascinatedBox** [FascinatedBox/RuinMyHistory#2]
A user should be able to configure the timeout delay. Additionally, begin the cycle when the user clicks a button (and allow them to stop it when clicking again).

**Comment by drifterr** [comment]
How about an option for a randomised interval, designed to cluster events together so that there isn't a predictable pattern to anything watching. Options might be added for times to avoid doing much, as well as average level of activity per day. 

Best method to add randomness is to have a set chance of doing something each smaller interval, and loading a page if the randomness agrees with the percent chance value.

**Comment by FascinatedBox** [comment]
This project started off with the intention of legit masking your browsing history. However, I've decided to keep it simple and make it be a thing that scrolls through entries and makes a bunch of junk dns queries.
