### ISSUE TITLE
Bracket missing, breaks script

### ISSUE THREAD

**Issue by daniel-law** [FascinatedBox/RuinMyHistory#8]
You missed an end bracket in the script and it breaks the page.
            function changeFrameSite() {
            popup.location.href = site_list[randint(0, site_list.length)];
            }

**Comment by TheWoofster** [comment]
is that why it doesnt work for me anymore?

**Comment by FascinatedBox** [comment]
@TheWoofster I believe so. I just now pushed a fix to it, and the script appears to be working again.

@daniel-law Thanks for reporting this. I hadn't gotten around to checking the script, because the other report made it seem as if the issue was a deeper one. My fault for not testing better.

The newly-pushed page should work now. If it doesn't please feel free to reopen this.
