### ISSUE TITLE
chrome blocking sites in the cycle

### ISSUE THREAD

**Issue by windykestrel** [FascinatedBox/RuinMyHistory#9]
Chrome's automatic protections are kicking in after just six or seven websites, blocking insecure sites and interrupting the cycle, and some websites will not load at all. This requires restarting the page over and over again-- definitely not productive. Is there a fix for this?

**Comment by FascinatedBox** [comment]
Ugh. The site list I pulled apparently wasn't checked for misbehaving websites. I could revert it to doing a linear scan of websites, but that won't solve the problem of some websites not loading. I could fix it, but not easily and not soon.

**Comment by windykestrel** [comment]
Hmm. Where does that leave users? This is such a great project, I wish I had the skills to contribute to a fix. Will you post when this is eventually resolved?

**Comment by FascinatedBox** [comment]
I put in a new issue about the future of the project. Beyond that, once it's more cleaned up, I can put a blog post up about it.

**Comment by FascinatedBox** [comment]
I ended up forgetting that this even existed. I made it on a whim one day and then promptly forgot about it. I never wrote about it because imo there wasn't really much to write about. IDK what might be causing this issue, but I'm going to close this as a won't fix because I don't see myself doing anything with this. Sorry.
